-- =============================================================================
-- invg_invoice_lines - Invoice service lines
-- =============================================================================

create table invg_invoice_lines (
  invg_invoice_line_id number generated by default on null as identity (start with 1) primary key not null
, invg_invoice_id      number not null
, line_number          number not null
, description          varchar2(4000 char)
, amount               number(18,2) default 0 not null
, created_by           varchar2(60 char) default
                       coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                       )
                       not null
, created_on           timestamp with local time zone default localtimestamp not null
, last_updated_by      varchar2(60 char)
, last_updated_on      timestamp with local time zone
, active_yn            varchar2(1 char) default 'Y' not null
, constraint fk_invg_invoice_lines_invoices foreign key (invg_invoice_id) references invg_invoices (invg_invoice_id)
, constraint ck_invg_invoice_lines_active_yn check (active_yn in ('Y', 'N'))
);

create index idx_invg_invoice_lines_invoice on invg_invoice_lines (invg_invoice_id);

begin
  execute immediate 'comment on table invg_invoice_lines is ''Invoice service lines.''';
end;
/
