-- =============================================================================
-- invg_invoices - Invoice header; references client, business, bank by ID
-- =============================================================================

create table invg_invoices (
  invg_invoice_id     number generated by default on null as identity (start with 1) primary key not null
, invoice_number      varchar2(50 char) not null
, issue_date          date not null
, include_due_date_yn varchar2(1 char) default 'Y' not null
, due_date            date
, payment_terms       varchar2(100 char)
, tax_rate            number(5,2) default 0
, other_amount        number(18,2) default 0
, notes               clob
, invg_client_id      number
, invg_business_id    number
, invg_bank_detail_id number
, created_by          varchar2(60 char) default
                      coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                      )
                      not null
, created_on          timestamp with local time zone default localtimestamp not null
, last_updated_by     varchar2(60 char)
, last_updated_on     timestamp with local time zone
, active_yn           varchar2(1 char) default 'Y' not null
, constraint ck_invg_invoices_active_yn check (active_yn in ('Y', 'N'))
, constraint ck_invg_invoices_include_due_date_yn check (include_due_date_yn in ('Y', 'N'))
, constraint fk_invg_invoices_client foreign key (invg_client_id) references invg_clients (invg_client_id)
, constraint fk_invg_invoices_business foreign key (invg_business_id) references invg_businesses (invg_business_id)
, constraint fk_invg_invoices_bank_detail foreign key (invg_bank_detail_id) references invg_bank_details (invg_bank_detail_id)
);

create unique index uk_invg_invoices_number on invg_invoices (invoice_number);

begin
  execute immediate 'comment on table invg_invoices is ''Invoice header; references client, business, bank by ID.''';
end;
/
