-- =============================================================================
-- invg_bank_details - Bank details lookup for invoice LOV
-- =============================================================================

create table invg_bank_details (
  invg_bank_detail_id number generated by default on null as identity (start with 1) primary key not null
, receiver_name      varchar2(255 char)
, bank_name          varchar2(255 char)
, routing_number     varchar2(50 char)
, bank_account_number varchar2(100 char)
, account_type       varchar2(50 char)
, bank_address       varchar2(4000 char)
, created_by         varchar2(60 char) default
                     coalesce(
                       sys_context('APEX$SESSION','app_user')
                     , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     , sys_context('userenv','session_user')
                     )
                     not null
, created_on         timestamp with local time zone default localtimestamp not null
, last_updated_by    varchar2(60 char)
, last_updated_on    timestamp with local time zone
, active_yn          varchar2(1 char) default 'Y' not null
, constraint ck_invg_bank_details_active_yn check (active_yn in ('Y', 'N'))
);

begin
  execute immediate 'comment on table invg_bank_details is ''Bank details lookup for invoice LOV.''';
end;
/
